package main

import (
	"archive/zip"
	"bytes"
	"fmt"
	"hash/crc32"
	"os"
	"path/filepath"

	"linglang/internal/compiler"
)

// Keep the launcher fixed so an executable can be renamed without changing
// escript's choice of entry module. Runtime policies match the ordinary runner.
func pack(path, program string, gcStress, gcStats bool) error {
	dir, err := os.MkdirTemp("", "linglang-pack-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(dir)
	files := compiler.RuntimeSources()
	files["linglang_program.erl"] = program
	files["linglang_cli.erl"] = "-module(linglang_cli).\n-export([main/1]).\nmain(Args) -> linglang_rt:set_arguments(Args), " + evaluationScript(gcStress, gcStats) + "\n"
	if err := buildSources(dir, files); err != nil {
		return err
	}
	var archive bytes.Buffer
	writer := zip.NewWriter(&archive)
	for _, name := range []string{"linglang_cli.beam", "linglang_program.beam", "linglang_rt.beam", "linglang_sup.beam", "linglang_server.beam", "linglang_io.beam"} {
		beam, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			return err
		}
		// OTP's archive loader needs sizes in each local ZIP header. CreateRaw
		// avoids Go's streaming data descriptors; BEAM files are stored directly.
		entry, err := writer.CreateRaw(&zip.FileHeader{
			Name: name, Method: zip.Store, CRC32: crc32.ChecksumIEEE(beam),
			CompressedSize64: uint64(len(beam)), UncompressedSize64: uint64(len(beam)),
		})
		if err != nil {
			return err
		}
		if _, err := entry.Write(beam); err != nil {
			return err
		}
	}
	if err := writer.Close(); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	// Publish only a complete executable; a failed pack leaves an old one usable.
	output, err := os.CreateTemp(filepath.Dir(path), ".linglang-pack-*")
	if err != nil {
		return err
	}
	defer os.Remove(output.Name())
	defer output.Close()
	if _, err := output.WriteString("#!/usr/bin/env escript\n%% Generated by linglang.\n%%! -escript main linglang_cli\n"); err != nil {
		return err
	}
	if _, err := output.Write(archive.Bytes()); err != nil {
		return err
	}
	if err := output.Chmod(0755); err != nil {
		return err
	}
	if err := output.Close(); err != nil {
		return err
	}
	if err := os.Rename(output.Name(), path); err != nil {
		return err
	}
	return nil
}

func protectSources(output string, sources []compiler.SourceFile) error {
	destination, err := filepath.Abs(output)
	if err != nil {
		return err
	}
	outputInfo, _ := os.Stat(output)
	for _, source := range sources {
		path, err := filepath.Abs(source.Filename)
		if err != nil {
			return err
		}
		info, _ := os.Stat(source.Filename)
		if path == destination || (info != nil && outputInfo != nil && os.SameFile(info, outputInfo)) {
			return fmt.Errorf("%s: refusing to overwrite source file %s", output, source.Filename)
		}
	}
	return nil
}
